### ISSUE TITLE
Loop after setting background

### ISSUE THREAD

**Issue by merken** [thiggy01/gdm-background#2]
Hi,

First of all, neat tool!
On Pop OS 20.10,after setting the background and testing it, it loops on the login screen. A restart is required to get out of this loop.

**Comment by thiggy01** [comment]
I don't know why this happens with some people. I just tested it in Pop OS 20.10 with my virtual machine on gnome boxes and it worked perfectly.
It was even faster than Ubuntu with no glitch when restarting gdm.
