### ISSUE TITLE
Error changing image in Pop OS! 20.10

### ISSUE THREAD

**Issue by josiahkeeler** [thiggy01/gdm-background#3]
```
Don't know how to handle /usr/share/gnome-shell/theme/Yaru/gnome-shell-theme.gresource~
Error opening destination file: No such file or directory
Could not move image file to work directory: No such file or directory

```

I get this error when trying to change images in Pop OS!. This used to work before. I have no idea what broke it. "Yaru" is not a theme. "Pop" is the only folder in that path.

**Comment by thiggy01** [comment]
I tested it on my machine running Pop OS 20.10 and it worked as expected by setting or restoring the gdm background.
I recompiled and uploaded the latest version to its github release page.
Please, download and test it again.

**Comment by josiahkeeler** [comment]
Thank you! My issue was with the compiled version. Cloning the repo and running it from the command line worked great. Works as expected now.
